### ISSUE TITLE
Cannot install theme

### ISSUE THREAD

**Issue by higorvaz** [rafi16jan/backend-theme#1]
Help please...
Put the backend-theme folder into my custom and restart odoo but the theme does not appear at Applications.
Also just update App List with no success.
Thanks a lot

**Comment by rafi16jan** [comment]
backend-theme folder is the root folder, put backend_theme in the backend-theme folder on your addons directory

**Comment by higorvaz** [comment]
Thanks, it appeared, but cannot complete the installation, could you help?



Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 845, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 915, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 799, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 777, in _tag_template
    return self._tag_record(record, data_node)
  File "/usr/lib/python2.7/dist-packages/odoo/tools/convert.py", line 707, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_model.py", line 1229, in _update
    record = record.create(values)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 362, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3834, in create
    self._fields[key].determine_inverse(record)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 1001, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 220, in _inverse_arch
    view.write(data)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 380, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3560, in write
    self._write(old_vals)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3711, in _write
    self._validate_fields(vals)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 1083, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
ParseError: "Error while validating constraint

Elemento '<xpath expr="div[@class='o_sub_menu_footer']">' n\xe3o pode ser localizado na vista principal

Contexto de erro:
Veja `None qweb`
[view_id: 761, xml_id: br_base.trust_menu_secondary, model: n/a, parent_id: 168]
None" while parsing None:101, near
<data inherit_id="web.menu_secondary" name="App Drawer - Secondary Menu">

        <xpath expr="//a[@class='o_sub_menu_logo']" position="replace"/>

        <xpath expr="//div[@class='o_sub_menu_footer']" position="replace"/>

        <xpath expr="//div[@class='o_sub_menu_content']/t" position="replace">

            <t t-foreach="menu_data['children']" t-as="menu">
			    <ul style="display: none" class="oe_secondary_menu nav navbar-nav" t-att-data-menu-parent="menu['id']">
				<li class="app-name">
					<span class="oe_menu_text">
						<t t-esc="menu['name']"/> 
					</span>
				</li>
				<li>
                    <t t-call="web.menu_secondary_submenu"/>
				</li>
                </ul>
            </t>

        </xpath>

    </data>
